---

- name: install packages
  yum: name={{ item }} state=present
  with_items:
  - haproxy
  - socat

- name: configure haproxy with Apache backend hosts
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: start haproxy service
  service: name=haproxy state=started enabled=yes

- name: enable the HAProxy frontend HTTP port + stats port
  firewalld: port={{ item }} permanent=true state=enabled
  with_items:
    - 80/tcp
    - 81/tcp
  notify: restart firewalld
