---

- name: install MySQL repo
  yum: name=http://dev.mysql.com/get/mysql-community-release-el7-5.noarch.rpm state=present

- name: install MySQL DB
  yum: name={{ item }}
  with_items:
    - mysql-community-server
    - MySQL-python

- name: start MySQL service
  service: name=mysqld state=started enabled=yes

- name: create test user
  mysql_user: name=aptest password=aptest123 priv=*.*:ALL host={{ item }} state=present
  with_items:
    - localhost
    - 127.0.0.1
    - ap1
    - ap2

- name: open up DB port 3306
  firewalld: port=3306/tcp permanent=true state=enabled
  notify: restart firewalld
