---

- name: restart firewalld
  service: name=firewalld state=restarted

- name: restart httpd
  service: name=httpd state=restarted

- name: restart db
  service: name=mysqld state=restarted

- name: restart haproxy
  service: name=haproxy state=restarted

- name: reload haproxy
  service: name=haproxy state=reloaded
