---

- name: restart haproxy
  service: name=haproxy state=restarted

- name: reload haproxy
  service: name=haproxy state=reloaded

- name: restart firewalld
  service: name=firewalld state=restarted
